### ISSUE TITLE
jrctl process list of IPs in text file for whitelist

### ISSUE THREAD

**Issue by Fealix13** [jetrails/jrctl#77]
I was wondering if we could get a way to process each IP address in a text file using the same ports specified in the whitelist command.

Something like
"jrctl firewall allow -af <<text file with newline separated IPS>> -p 80.443"

**Comment by null93** [comment]
Sounds good, we can make it look closer to this: `jrctl firewall allow -f ADDRESS_ON_EACH_LINE.txt -p 80,443`.

**Comment by null93** [comment]
Will implement for allow, unallow, deny, and undeny
