### ISSUE TITLE
Ability to Reload/Enable/Disable Services

### ISSUE THREAD

**Issue by Fealix13** [jetrails/jrctl#82]
It would be good to be able to reload a service in addition to being able to restart them. 

jrctl server reload nginx

Something like the above.

**Comment by null93** [comment]
@Fealix13 at this time, we are not looking to mimic everything that systemctl can do. This is definitely a valuable feature but not going to be implemented at this time. Thank you for the suggestion!

**Comment by null93** [comment]
@Fealix13 Reopening because we are gonna do even more than reload! Look forward to the following verbs to be added:

- reload
- enable (enables and starts)
- disable (disables and stops)
